src/clinic/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'clinic'
urlpatterns = [
    url(r'^$', views.ListPatients.as_view(),
        name='patients'),
    url(r'(?P<pk>\d+)/$', views.DetailPatient.as_view(),
        name='detail_patient'),
    url(r'new/$', views.CreatePatient.as_view(),
        name='create_patient'),
    url(r'results/$', views.PatientSearchListView.as_view(),
        name='search'),
    url(r'patient(?P<pk1>\d+)-consultation(?P<pk2>\d+)\.pdf$',
        views.consultation_pdf, name='consultation_pdf'),
    url(r'consultations/new/$', views.CreateConsultation.as_view(),
        name='create_consultation'),
    url(r'consultations/$', views.ListConsultations.as_view(),
        name='consultations'),
]

src/courrier/urls.py
from django.conf.urls import url, include
from django.conf import settings
from . import views

app_name = 'courrier'
urlpatterns = [
    url(r'patient(?P<pk1>\d+)-courrier(?P<pk2>\d+)\.mkiv$',
        views.courrier_mkiv, name='courrier_mkiv'),
    url(r'patient(?P<pk1>\d+)-stomato(?P<pk2>\d+)\.pdf$',
        views.stomato_pdf, name='stomato_pdf'),
    url(r'patient(?P<pk1>\d+)-certificat(?P<pk2>\d+)\.pdf$',
        views.certificat_pdf, name='certificat_pdf'),
    url(r'patient(?P<pk1>\d+)-lettre(?P<pk2>\d+)\.pdf$',
        views.courrier_pdf, name='courrier_pdf'),
    url(r'patient(?P<pk1>\d+)-ordonnance(?P<pk2>\d+)\.pdf$',
        views.ordonnance_pdf, name='ordonnance_pdf'),
    url(r'patient(?P<pk1>\d+)-arret(?P<pk2>\d+)\.pdf$',
        views.arret_pdf, name='arret_pdf'),
]

src/my_proj/urls.py
"""
with the new version of django 2.0 or higher, urls.py face the biggest rework
"""
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# import des fichier locaux urls.py
import profiles.urls
import clinic.urls
import courrier.urls
import accounts.urls
from . import views
# from clinic.views import current_admission

urlpatterns = [
    url(r'^accueil/$', views.HomePage.as_view(),
        name='home'),
    url(r'^about/$', views.AboutPage.as_view(),
        name='about'),
    url(r'^users/', include(profiles.urls,
                            namespace='profiles')),
    path(r'admin/', admin.site.urls),
    url(r'^me/', include(accounts.urls, namespace='accounts')),
    url(r'^clinic/', include(clinic.urls, namespace='clinics')),
    url(r'^courrier/', include(courrier.urls, namespace='courriers'))
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/profiles/urls.py
from django.conf.urls import url
from . import views
app_name = 'profile'
urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/clinic/views.py
from django.shortcuts import render, get_list_or_404
from django.urls import reverse, reverse_lazy
# from django.core.urlresolvers import reverse, reverse_lazy
from .models import Patient, Consultation, Stress
from courrier.models import Courrier, Certificat, Arret, Stomato, Ordonnance
from django.views.generic import (ListView, DetailView, TemplateView,
                                  CreateView, UpdateView)
from django.http import HttpResponse
from django.template.loader import get_template  # render_to_string
from subprocess import Popen, PIPE
import tempfile
import os
import operator
from django.db.models import Q
from six.moves import reduce
# Create your views here.

class HomePage(TemplateView):
    template_name = "index.html"


class AboutPage(TemplateView):
    template_name = "about.html"


class ListPatients(ListView):
    model = Patient
    context_object_name = 'patients'


class CreatePatient(CreateView):
    model = Patient
    fields = '__all__'
    template_name = "clinic/create_patient.html"
    success_url = reverse_lazy('clinic:patients')


class DetailPatient(DetailView):
    model = Patient
    context_object_name = 'patient'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(DetailPatient, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
#        context['admissions'] = Admission.objects.filter(patient=self.object)
        context['consultations'] = Consultation.objects.filter(patient=self.object)
        context['ordonnances'] = Ordonnance.objects.filter(patient=self.object)
        context['stomatos'] = Stomato.objects.filter(patient=self.object)
        context['courriers'] = Courrier.objects.filter(patient=self.object)
        context['certificats'] = Certificat.objects.filter(patient=self.object)
        context['arrets'] = Arret.objects.filter(patient=self.object)
        context['stresses'] = Stress.objects.filter(patient=self.object)
#        context['coronarographies'] = Coronarographie.objects.filter(patient=self.object)
#        context['stimulations'] = Stimulation.objects.filter(patient=self.object)
        return context


class PatientSearchListView(ListPatients):
    """
    Display the patient List page filtered by the search query.
    """
    paginate_by = 10

    def get_queryset(self):
        result = super(PatientSearchListView, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(phone__icontains=q) for q in query_list))
                # reduce(operator.and_,
                       # (Q(tags__icontains=q) for q in query_list))
            )

        return result
""" consultation """

class ListConsultations(ListView):
    model = Consultation
    context_object_name = 'consultations'

class CreateConsultation(CreateView):
    model = Consultation
    fields = '__all__'
    template_name = "app/create_consultation.html"
    success_url = reverse_lazy('clinique:consultations')



def consultation_pdf(request, pk2, pk1):
    entry = Consultation.objects.get(pk=pk2)
    source = Patient.objects.get(pk=pk1)
#   context = Context({ 'consultation': entry, 'patient': source })
    context = dict({'consultation': entry, 'patient': source})
    template = get_template('clinic/consultation.tex')
    rendered_tpl = template.render(context, request).encode('utf-8')
    # Python3 only. For python2 check out the docs!
    with tempfile.TemporaryDirectory() as tempdir:
        # Create subprocess, supress output with PIPE and
        # run latex twice to generate the TOC properly.
        # Finally read the generated pdf.
        for i in range(2):
            process = Popen(
                ['xelatex', '-output-directory', tempdir],
                stdin=PIPE,
                stdout=PIPE,
            )
            process.communicate(rendered_tpl)
        with open(os.path.join(tempdir, 'texput.pdf'), 'rb') as f:
            pdf = f.read()
    r = HttpResponse(content_type='application/pdf')
    r.write(pdf)
    return r


# def alternative_pdf(request, pk2, pk1):
#     title = get_object_or_404(Consultation, pk=pk2).patient

#     template_file = 'app/consultation.tex'
#     t = get_template(template_file)
#     entry = Certificat.objects.get(pk=pk2)
#     source = Patient.objects.get(pk=pk1)
#     context = Context({ 'certificat': entry, 'patient': source })
#         f.write(smart_str(t.render(context)))
#     return HttpResponseRedirect('/app/%s.pdf' % consultation.patient)


# Reportlab stuff
#
# def headerFooterLayout(canvas, doc):
#     canvas.saveState()
#     canvas.setPageSize(self.pagesize)
#     # add header/footer
#     canvas.restoreState()

# def emptyLayout(canvas, doc):
#     canvas.saveState()
#     canvas.setPageSize(self.pagesize)
#     canvas.restoreState()

# pHeight, pWidth = self.pagesize
# myFrame = Frame(0, 0, pHeight, pWidth, id='myFrame')

# headerFooterTemplate = PageTemplate(id='headerFooterTemplate',
#                                     frames=[myFrame],
#                                     onPage=headerFooterLayout)

# emptyTemplate = PageTemplate(id='emptyTemplate',
#                              frames=[myFrame],
#                              onPage=emptyLayout)

# elements = []
# elements.append(Paragraph('blah', style)
# elements.append(NextPageTemplate('emptyTemplate'))
# elements.append(PageBreak())
# elements.append(Paragraph('last page', style)

# doc = BaseDocTemplate(buffer,
#                       rightMargin=72,
#                       leftMargin=72,
#                       topMargin=72,
#                       bottomMargin=72)

# doc.addPageTemplates([headerFooterTemplate, emptyTemplate])

# doc.build(elements)





#from django.http import HttpResponse
#from reportlab.pdfgen import canvas

#def invoice_to_response(request, invoice):
#    response = HttpResponse(mimetype='application/pdf')
#    p = canvas.Canvas(response, pagesize=A4, pageCompression = 0)
#    # here I draw on 'p' like p.setFillColor(black)
#    p.showPage()
#    p.save()
#    return response

src/clinic/templates/clinic/consultation_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}Consultation{% endblock %}

{% block container %}
<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
        <h1>{{ consultation.patient }}  <small>le {{consultation.consultation_date}}</h1>

   <!-- à remplacer par edit consultation  {% if editable %}
  <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
      {% endif %} -->
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'logo.png' 140x140 crop %}">
    </div>
  </div>
</div>


<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">Données générales</li>
        <li class="list-group-item text-left"><strong>Consultation du {{ consultation.consultation_date }}</strong></li>

	  <!--  <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span> -->
	<!--    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>-->


        <li class="list-group-item text-left">Medecin traitant <strong>Docteur Yahyaoui Mohamed Kaddour</strong></li>
        <li class="list-group-item text-left"><a href="{% url 'consultation_pdf' pk=consultation.pk %}" >Imprimer rapport <span class ="glyphicon glyphicon-print"></span></a></li>

      <li class="list-group-item text-left"><a href="{% url 'update_consultation' pk=consultation.pk %}" >éditer <span class ="glyphicon glyphicon-pencil"></span></a></li>
      </ul>
    </div>



    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">Observation</div>
        <div class="panel-body">
	   <h2>{{ consultation.patient }}</h2>
         <p> {% if consultation.emergency = True %}consultation dans le cadre de l'urgence pour {% else %} Le patient a séjourné dans notre service du {{ consultation.consultation_date }} au {{ consultation.date_sortie }} pour{% endif %} {% for motif in consultation.motif_consultation.all %}  {{ motif  }}.{% endfor %}</p>

         <div><h3>Histoire de la maladie</h3>
           <p>{{  consultation.histoire }}</p>

         </div>
         <div class="col-md4">
             <h3>Examen clinique</h3>
                <h4>Signes fonctionnels</h4>
                <ul>
      {% if consultation.fever = True %} <li>fièvre</li>{% endif %}
      {% if consultation.dyspnea_nyha = '1' %} <li>Eupnéique au repos</li>{% else %}<li>Dyspnée au stade {{ consultation.dyspnea_nyha }} de la <em>NYHA</em></li>{% endif %}
     {% if consultation.angina_scc = '1' %} <li>Absence d'angor</li>{% else %}<li>Angor au stade {{ consultation.angina_scc }} de la <em>SCC</em></li>{% endif %}
     {% if consultation.syncope = True %} <li>Syncope</li>{% endif %}

               </ul>
               <h4>Signes physiques</h4>
                   <p> L'examen clinique retrouve à l'auscultation: {{ consultation.auscultation }} avec une  Fréquence cardiaque à = {{ consultation.heart_rate}} Bpm.<br>
                     En périphérie les pouls sont {{ consultation.pulse }} avec une  PA = {{ consultation.systolic_bp }}/{{ consultation.diastolic_bp }}mmHg<br>
                   </p>
         </div>

         <div class="col-md4">
                 <h3>ECG</h3>
                   <p>Le rythme est en {% if consultation.rythm = 'S' %}sinusal{% elif consultation.rythm = 'F' %}fibrillation atriale{% elif consultation.rythm = 'R'%}flutter auriculaire{% elif consultation.rythm = 'T' %}tacchycardie ventriculaire{% elif consultation.rythm = 'P' %}électro stimulé{% endif %} à fréquence cardiaque de {{ consultation.freq}} puls/min.<br>
                     {% if consultation.bundle_block = 'G' %}Il existe un block de branche gauche.<br>{% elif consultation.bundle_block = 'D' %}Il existe un block de branche droit.<br>{% endif %}
                     {% if consultation.hypertrophy = True %}On note aussi une hypertrophie ventriculaire gauche électrique.<br>{% endif %}
                     <p>sur le plan ischémique: {% if consultation.lesion = 'S' %} une lésion en septal{% elif consultation.lesion = 'A' %} une lésion en antérieur{% elif consultation.lesion = 'L' %} une lésion en latéral{% elif consultation.lesion = 'P' %} une lésion en postérieur{% else %}absence de lésions électriques{% endif %},
                       {% if consultation.ischaemia = 'S' %} une ischémie en septal{% elif consultation.ischaemia = 'A' %} une ischémie en antérieur{% elif consultation.ischaemia = 'L' %} une ischémie en latéral{% elif consultation.ischaemia = 'P' %} une ischémie postérieur{% else %}absence d'ischémie électrique{% endif %},
                       {% if consultation.t_inversion = 'S' %} onde T inversée en septal{% elif consultation.t_inversion = 'A' %} onde T inversée en antérieur{% elif consultation.t_inversion = 'L' %} onde T inversée en en latéral{% elif consultation.t_inversion = 'P' %} onde T inversée en postérieur{% endif %}<br>
                       Le QT corrigé est estimé à {{ consultation.corrected_qt }} msec
                       .<br>

                   </p>
          </div>
          <div><h3>Téléthorax</h3>
            <p>Le téléthorax retrouve: {{ consultation.telethorax }}.<p>
              </div>

              <div><h3>Échocardiographie {{ date_echo }}</h3>
                <p>À l'échocardiographie on a : {{ consultation.echocoeur }}.<p>
                  {% if eto %}<p>{{ consultation.eto }}</p>{% endif %}
                  </div>




            <div><h2>En résumé</h2>
              <p>{{ consultation.resume }}</p>
            </div>




            </div>


            <div><h2>Sortie</h2>


              <h3>Dispositions complémentaires</h3>
             <p>{{ consultation.dispositions }}</p>



            </div>

     </div>
    </div>
  </div>
</div>
</div>

{% endblock  %}

src/clinic/templates/clinic/consultation_list.html
{% extends "base.html" %}
{% load staticfiles %}
<head>
<meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="description" content="">
   <meta name="author" content="">


   <!-- Bootstrap Core CSS -->
   <link href={% static 'clinique/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    {% block styles %}
    <link href= {% static 'clinique/css/blog-home.css' %}" rel="stylesheet">
    {% endblock styles %}

{% block title %}{{ block.super }}Consultations{% endblock %}
</head>

{% block content %}

<table class="table table-compact table-striped table-hover">
        <tr>
            <th>Patient </th>
            <th>Date de consultation </th>
            <th>Urgence </th>
            <th>Motifs </th>
            <th>Conclusion</th>

            <th>Dispositions complémentaires</th>
            <th>Éditer</th>

        </tr>

        {% for consultation in consultations %}
        <tr>
            <td><a href="#"><strong>{{ consultation.patient }} - {{ patient.birth }}</strong></a></td>

            <td><a href="#"><strong>{{ consultation.consultation_date }}</strong></a></td>

            <td>{% if consultation.emergency == True %} oui {% else %} non {% endif %}</td>
            <td>{% for motif in consultation.motif_consultation.all %} {{ motif }} {% endfor %}</td>
            <td>{{ consultation.resume }}</td>
            <td>{{ consultation.dispositions }} </td>
            <td><a href="#"><span class ="glyphicon glyphicon-pencil" aria-hidden="true"></span></td></a>

        </tr>
        {% endfor %}
    </table>
    <hr>
    <a class="btn btn-default " href="#" >

        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nouvelle consultation
    </a>


</div>





{% endblock content %}


    {% block scripts %}
    <script src="{% static 'site/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site/js/site.js' %}"></script>
    {% endblock scripts %}

src/clinic/templates/clinic/create_consultation.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

   <link href={% static 'clinique/css/bootstrap.min.css' %}" rel="stylesheet">

   <!-- Custom CSS -->
   {% block styles %}
   <link href= {% static 'clinique/css/blog-home.css' %}" rel="stylesheet">
   {% endblock styles %}

{% block title %}{{ block.super }}Consultation{% endblock title %}
 <div class="col-md-8">
      <div class="well">
        <form method="POST" action="."> {% csrf_token %}
        {{ form | crispy }}
          <input type="submit" value="valider" class="btn btn-success btn-lg btn-block" >
      </form>
      </div>
      </div>


{% block content %}
   <div class="container">
       <div class="col-md-8">
      <div class="well">
        <form method="POST" action="."> {% csrf_token %}
        {{ form | crispy }}
          <input type="submit" value="valider" class="btn btn-success btn-lg btn-block" >
      </form>
      </div>
      </div>
      </div>
      
{% endblock content %}
{% block scripts %}
<script src="{% static 'clinique/js/jquery.min.js' %}"></script>
<script src="{% static 'clinique/js/bootstrap.min.js' %}"></script>
<script src="{% static 'clinique/js/blog-home.js' %}"></script>
{% endblock scripts %}

src/clinic/templates/clinic/create_patient.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

   <link href={% static 'clinique/css/bootstrap.min.css' %}" rel="stylesheet">

   <!-- Custom CSS -->
   {% block styles %}
   <link href= {% static 'clinique/css/blog-home.css' %}" rel="stylesheet">
   {% endblock styles %}

{% block title %}{{ block.super }}Nouveau patient{% endblock title %}
 <div class="col-md-8">
      <h1>Nouveau patient</h1>
      <div class="well">
        <form method="POST" action="."> {% csrf_token %}
        {{ form | crispy }}
          <input type="submit" value="valider" class="btn btn-success btn-lg btn-block" >
      </form>
      </div>
      </div>


{% block content %}
   <div class="container">
       <div class="col-md-8">
      <h1>Nouveau patient</h1>
      <div class="well">
        <form method="POST" action="."> {% csrf_token %}
        {{ form | crispy }}
          <input type="submit" value="valider" class="btn btn-success btn-lg btn-block" >
      </form>
      </div>
      </div>
      </div>
      
{% endblock content %}
{% block scripts %}
<script src="{% static 'clinique/js/jquery.min.js' %}"></script>
<script src="{% static 'clinique/js/bootstrap.min.js' %}"></script>
<script src="{% static 'clinique/js/blog-home.js' %}"></script>
{% endblock scripts %}

src/clinic/templates/clinic/patient_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}


{% block title %}{{ block.super }}Patient {{ patient.name }}{% endblock title %}




{% block container %}
<hr>
     <h2>{{ patient.name }}</h2>



    <table class="table table-compact table-striped table-hover">
        <tr>
            <th>consultation</th>
            <th>Motifs </th>
            <th>Urgence?</th>
            <th>Resumé clinique</th>
            <th>dispositions complémentaires</th>
            <th>Éditer</th>
            <th>tags</th>

       </tr>

        {% for consultation in consultations %}
        <tr>
            <td><a href="{% url 'clinics:consultation_pdf' pk1=patient.pk pk2=consultation.pk %}"><span class ="glyphicon glyphicon-print" aria-hidden="true"></span> <strong>{{ consultation.consultation_date }}</strong></a></td>


            <td>{% for motif in consultation.motif_consultation.all %} {{ motif }} {% endfor %}</td>
            <td>{% if consultation.emergency == True %} oui {% else %} non {% endif %}</td>
            <td>{{ consultation.resume }}</td>
            <td>{{ consultation.dispositions }}</td>

            <td><a href="#"><span class ="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
            <td>{% for tag in patient.tags.all %} <span class="label label-warning">{{ tag }}</span> {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <hr>


    <h3>Document médicaux</h3>

    <table class="table table-compact table-striped table-hover">
        <tr>
            <th>Courriers</th>
            <th>Ordonnances</th>
            <th>Stress echo</th>
            <th>coroscan</th>
       </tr>
       <tr>
           <th>
               <ul>
{% for courrier in courriers   %}
                   <li>   <a href="{% url 'courriers:courrier_mkiv' pk1=patient.pk pk2=courrier.pk %}"><span class ="glyphicon glyphicon-print" aria-hidden="true"></span> {{ courrier.patient }} - {{ courrier.courrier_date }}</a>

  </li>

{% endfor %}
                    {% for certificat in certificats %}
 <li>
        
           <a href="{ % url 'courriers:certficat_pdf' pk1=patient.pk pk2=certificat.pk % #}"><span class ="glyphicon glyphicon-print" aria-hidden="true"></span> {{ certificat.patient }}</a>   </li>
 
{% endfor %}
                   <li>     </li>
                   <li>     </li>

               </ul>

           </th>
        <tr>
         
    </table>
    <hr>








{% endblock container %}


{% block scripts %}
<script src="{% static 'clinique/js/jquery.min.js' %}"></script>
<script src="{% static 'clinique/js/bootstrap.min.js' %}"></script>
<script src="{% static 'clinique/js/blog-home.js' %}"></script>
{% endblock scripts %}

src/clinic/templates/clinic/patient_list.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}




{% block title %}{{ block.super }}Patients{% endblock %}


{% block container %}

<h1> Liste des atients</h1>
<hr>


    <table class="table table-compact table-striped table-hover">
        <tr>
            <th>Patient </th>
            <th>Date de naissance </th>
            <th>Adresse </th>
            <th>Téléphone</th>
            <th>Assurance</th>

            <th>Date de 1° consultation</th>
            <th>Allergies connues</th>
            <th>Tags</th>

            <th>Éditer</th>

        </tr>

        {% for patient in patients %}
        <tr>
            <td><a href="{% url 'clinics:detail_patient' pk=patient.pk %}"><strong>{{ patient.name }}</strong></a></td>


            <td>{{ patient.birth }}</td>
            <td>{{ patient.adresse }}</td>
            <td>{{ patient.phone }}</td>
            <td>{% if patient.assurance == 'C' %}CNAS {% else %}CASNOS {% endif %}</td>
            <td>{{patient.first_admission }}</td>
            <td>{{ patient.allergy }}</td>

            <td>{% for tag in patient.tags.all %} <span class="label label-warning">{{ tag }}</span> {% endfor %}
                <td><a href="#"><span class ="glyphicon glyphicon-pencil" aria-hidden="true"></span></td></a>

        </tr>
        {% endfor %}
    </table>
    <hr>
    <a class="btn btn-default " href="#" >

        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ajouter patient
    </a>


</div>





{% endblock container %}


{% block scripts %}
<script src="{% static 'clinique/js/jquery.min.js' %}"></script>
<script src="{% static 'clinique/js/bootstrap.min.js' %}"></script>
<script src="{% static 'clinique/js/blog-home.js' %}"></script>
{% endblock scripts %}

src/clinic/templates/clinic/search_results.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}


{% block title %}{{ block.super }}Results{% endblock %}


{% block container %}




Vous avez cherché "{{ query }}" et les résultats sont listés plus bas:

<ul>
    {% for object in objects %}
    <li> {{ object }}</li>
    {% endfor %}
</ul>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}