src/accounts/urls.py
from django.conf.urls import url

from . import views
app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/clinic/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'clinic'
urlpatterns = [
    url(r'^$', views.ListPatients.as_view(),
        name='patients'),
    url(r'(?P<pk>\d+)/$', views.DetailPatient.as_view(),
        name='detail_patient'),
    url(r'new/$', views.CreatePatient.as_view(),
        name='create_patient'),
    url(r'results/$', views.PatientSearchListView.as_view(),
        name='search'),
    url(r'patient(?P<pk1>\d+)-consultation(?P<pk2>\d+)\.pdf$',
        views.consultation_pdf, name='consultation_pdf'),
    url(r'consultations/new/$', views.CreateConsultation.as_view(),
        name='create_consultation'),
    url(r'consultations/$', views.ListConsultations.as_view(),
        name='consultations'),
]

src/templates/_brandname.html
Kardio

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">Bienvenue en cardiologie</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">La superbe équipe de cardio</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Dr Yahyaoui Mohamed Kaddour {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}